name: aio_workout
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.2
  firebase_core: ^3.12.0
  firebase_crashlytics: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  image_path: "assets/icon/01.png"
  
  # Android Configuration
  android:
    enable: true
    adaptive_icon_background: "#02569B"
    adaptive_icon_foreground: "assets/icon/01.png"
    adaptive_icon_inset: 25%
    
  # iOS Configuration  
  ios:
    enable: true
    icon_size: 1024
    icon_background_color: "#02569B"
    
  # Web Configuration
  web:
    enable: true
    image_path: "assets/icon/01.png"
    background_color: "#02569B"
    theme_color: "#02569B"
    
  # Windows Configuration
  windows:
    enable: true
    image_path: "assets/icon/01.ico"
    
  # macOS Configuration
  macos:
    enable: true
    image_path: "assets/icon/01.png"

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
