import 'package:flutter/material.dart';
import 'achievement_category.dart';
import 'achievement_definition.dart';

const allAchievementDefinitions = <AchievementDefinition>[
  // ── Workout (8) ──
  AchievementDefinition(
    id: 'first_steps',
    title: 'First Steps',
    description: 'Complete your first workout',
    icon: Icons.directions_run,
    category: AchievementCategory.workout,
    target: 1,
    progressLabel: 'Workouts',
    sortOrder: 0,
  ),
  AchievementDefinition(
    id: 'workout_10',
    title: 'Getting Started',
    description: 'Complete 10 workouts',
    icon: Icons.fitness_center,
    category: AchievementCategory.workout,
    target: 10,
    progressLabel: 'Workouts',
    sortOrder: 1,
  ),
  AchievementDefinition(
    id: 'workout_25',
    title: 'Quarter Century',
    description: 'Complete 25 workouts',
    icon: Icons.fitness_center,
    category: AchievementCategory.workout,
    target: 25,
    progressLabel: 'Workouts',
    sortOrder: 2,
  ),
  AchievementDefinition(
    id: 'workout_50',
    title: 'Half Century',
    description: 'Complete 50 workouts',
    icon: Icons.fitness_center,
    category: AchievementCategory.workout,
    target: 50,
    progressLabel: 'Workouts',
    sortOrder: 3,
  ),
  AchievementDefinition(
    id: 'workout_100',
    title: 'Century Club',
    description: 'Complete 100 workouts',
    icon: Icons.fitness_center,
    category: AchievementCategory.workout,
    target: 100,
    progressLabel: 'Workouts',
    sortOrder: 4,
  ),
  AchievementDefinition(
    id: 'core_crusher',
    title: 'Core Crusher',
    description: 'Complete 10 core-focused workouts',
    icon: Icons.fitness_center,
    category: AchievementCategory.workout,
    target: 10,
    progressLabel: 'Core workouts',
    sortOrder: 5,
  ),
  AchievementDefinition(
    id: 'upper_champ',
    title: 'Upper Body Champ',
    description: 'Complete 10 upper body workouts',
    icon: Icons.pan_tool,
    category: AchievementCategory.workout,
    target: 10,
    progressLabel: 'Upper body workouts',
    sortOrder: 6,
  ),
  AchievementDefinition(
    id: 'lower_legend',
    title: 'Lower Body Legend',
    description: 'Complete 10 lower body workouts',
    icon: Icons.directions_walk,
    category: AchievementCategory.workout,
    target: 10,
    progressLabel: 'Lower body workouts',
    sortOrder: 7,
  ),
  AchievementDefinition(
    id: 'full_fusion',
    title: 'Full Body Fusion',
    description: 'Complete 10 full body workouts',
    icon: Icons.local_fire_department,
    category: AchievementCategory.workout,
    target: 10,
    progressLabel: 'Full body workouts',
    sortOrder: 8,
  ),
  AchievementDefinition(
    id: 'volume_100',
    title: 'Volume 100',
    description: 'Complete 100 total exercise sets',
    icon: Icons.looks_one,
    category: AchievementCategory.workout,
    target: 100,
    progressLabel: 'Sets',
    sortOrder: 9,
  ),
  AchievementDefinition(
    id: 'volume_500',
    title: 'Volume 500',
    description: 'Complete 500 total exercise sets',
    icon: Icons.looks_two,
    category: AchievementCategory.workout,
    target: 500,
    progressLabel: 'Sets',
    sortOrder: 10,
  ),
  AchievementDefinition(
    id: 'volume_1000',
    title: 'Volume 1K',
    description: 'Complete 1,000 total exercise sets',
    icon: Icons.looks_3,
    category: AchievementCategory.workout,
    target: 1000,
    progressLabel: 'Sets',
    sortOrder: 11,
  ),

  // ── Consistency (5) ──
  AchievementDefinition(
    id: 'week_warrior',
    title: 'Week Warrior',
    description: 'Complete a full week (5 workouts)',
    icon: Icons.shield,
    category: AchievementCategory.consistency,
    target: 5,
    progressLabel: 'Week 1 workouts',
    sortOrder: 0,
  ),
  AchievementDefinition(
    id: 'dedicated',
    title: 'Dedicated',
    description: 'Complete 4 consecutive weeks',
    icon: Icons.star,
    category: AchievementCategory.consistency,
    target: 4,
    progressLabel: 'Consecutive weeks',
    sortOrder: 1,
  ),
  AchievementDefinition(
    id: 'halfway',
    title: 'Halfway There',
    description: 'Complete 6 weeks',
    icon: Icons.trending_up,
    category: AchievementCategory.consistency,
    target: 6,
    progressLabel: 'Weeks completed',
    sortOrder: 2,
  ),
  AchievementDefinition(
    id: 'graduate',
    title: 'Program Graduate',
    description: 'Complete all 12 weeks',
    icon: Icons.school,
    category: AchievementCategory.consistency,
    target: 12,
    progressLabel: 'Weeks completed',
    sortOrder: 3,
  ),
  AchievementDefinition(
    id: 'streak_5',
    title: 'Streak Master',
    description: 'Complete 5 workouts in a row',
    icon: Icons.whatshot,
    category: AchievementCategory.consistency,
    target: 5,
    progressLabel: 'Day streak',
    sortOrder: 4,
  ),

  // ── Steps (4) ──
  AchievementDefinition(
    id: 'steps_10k',
    title: 'Ten Thousand',
    description: 'Accumulate 10,000 total steps',
    icon: Icons.directions_run,
    category: AchievementCategory.steps,
    target: 10000,
    progressLabel: 'Total steps',
    sortOrder: 0,
  ),
  AchievementDefinition(
    id: 'steps_50k',
    title: 'Walker',
    description: 'Accumulate 50,000 total steps',
    icon: Icons.directions_run,
    category: AchievementCategory.steps,
    target: 50000,
    progressLabel: 'Total steps',
    sortOrder: 1,
  ),
  AchievementDefinition(
    id: 'steps_100k',
    title: 'Explorer',
    description: 'Accumulate 100,000 total steps',
    icon: Icons.directions_run,
    category: AchievementCategory.steps,
    target: 100000,
    progressLabel: 'Total steps',
    sortOrder: 2,
  ),
  AchievementDefinition(
    id: 'steps_500k',
    title: 'Marathoner',
    description: 'Accumulate 500,000 total steps',
    icon: Icons.directions_run,
    category: AchievementCategory.steps,
    target: 500000,
    progressLabel: 'Total steps',
    sortOrder: 3,
  ),

  // ── Hydration (3) ──
  AchievementDefinition(
    id: 'water_10L',
    title: 'Well Hydrated',
    description: 'Consume 10 liters of water total',
    icon: Icons.water_drop,
    category: AchievementCategory.hydration,
    target: 10,
    progressLabel: 'Total liters',
    sortOrder: 0,
  ),
  AchievementDefinition(
    id: 'water_50L',
    title: 'Aqua Master',
    description: 'Consume 50 liters of water total',
    icon: Icons.water_drop,
    category: AchievementCategory.hydration,
    target: 50,
    progressLabel: 'Total liters',
    sortOrder: 1,
  ),
  AchievementDefinition(
    id: 'water_100L',
    title: 'Hydro Homie',
    description: 'Consume 100 liters of water total',
    icon: Icons.water_drop,
    category: AchievementCategory.hydration,
    target: 100,
    progressLabel: 'Total liters',
    sortOrder: 2,
  ),

  // ── Weight (3) ──
  AchievementDefinition(
    id: 'first_weight',
    title: 'Starting Point',
    description: 'Log your first weight entry',
    icon: Icons.monitor_weight_outlined,
    category: AchievementCategory.weight,
    target: 1,
    progressLabel: 'Weight entries',
    sortOrder: 0,
  ),
  AchievementDefinition(
    id: 'weight_consistent',
    title: 'Consistent Logger',
    description: 'Log weight 7 times',
    icon: Icons.monitor_weight_outlined,
    category: AchievementCategory.weight,
    target: 7,
    progressLabel: 'Weight logs',
    sortOrder: 1,
  ),
  AchievementDefinition(
    id: 'goal_setter',
    title: 'Goal Setter',
    description: 'Set a weight goal',
    icon: Icons.flag,
    category: AchievementCategory.weight,
    target: 1,
    progressLabel: 'Goal set',
    sortOrder: 2,
  ),

  // ── Special / Hidden (3) ──
  AchievementDefinition(
    id: 'profile_complete',
    title: 'Who Am I?',
    description: 'Fill in all profile fields',
    icon: Icons.person,
    category: AchievementCategory.special,
    target: 1,
    progressLabel: 'Profile',
    isHidden: true,
    sortOrder: 0,
  ),
  AchievementDefinition(
    id: 'early_bird',
    title: 'Early Bird',
    description: 'Complete 5 workouts before 8 AM',
    icon: Icons.wb_sunny,
    category: AchievementCategory.special,
    target: 5,
    progressLabel: 'Early workouts',
    isHidden: true,
    sortOrder: 1,
  ),
  AchievementDefinition(
    id: 'night_owl',
    title: 'Night Owl',
    description: 'Complete 5 workouts after 9 PM',
    icon: Icons.nightlight_round,
    category: AchievementCategory.special,
    target: 5,
    progressLabel: 'Late workouts',
    isHidden: true,
    sortOrder: 2,
  ),
];
